<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sitecore.CH.Base\Sitecore.CH.Base.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Sample\Domain\" />
  </ItemGroup>
</Project>